import AppProvider from '@/components/providers/AppProvider';
import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider
			afterSignOutUrl={'/sign-in'}
			appearance={{
				elements: {
					formButtonPrimary: 'bg-primary hover:bg-primary/90 text-sm !shadow-none',
				}
			}}
		>
			<html lang="en">
				<body className={inter.className} suppressHydrationWarning={true}>
					<AppProvider>
						{children}
					</AppProvider>
					<Toaster richColors />
				</body>
			</html>
		</ClerkProvider>
	);
}
